#pragma once

public delegate void FrontConnect();

public delegate void DisConnected(int reason);
public delegate void HeartBeatWarning(int pTimeLapes);
public delegate void ErrRtnBankToFutureByFuture(CTPCommon::CThostFtdcReqTransferField pReqTransfer, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnFutureToBankByFuture(CTPCommon::CThostFtdcReqTransferField pReqTransfer, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnOrderAction(CTPCommon::CThostFtdcOrderActionField pOrderAction, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnOrderInsert(CTPCommon::CThostFtdcInputOrderField pInputOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnQueryBankBalanceByFuture(CTPCommon::CThostFtdcReqQueryAccountField pReqQueryAccount, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnRepealBankToFutureByFutureManual(CTPCommon::CThostFtdcReqRepealField pReqRepeal, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void ErrRtnRepealFutureToBankByFutureManual(CTPCommon::CThostFtdcReqRepealField pReqRepeal, CTPCommon::CThostFtdcRspInfoField pRspInfo);
public delegate void RspError(CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspFromBankToFutureByFuture(CTPCommon::CThostFtdcReqTransferField pReqTransfer, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspFromFutureToBankByFuture(CTPCommon::CThostFtdcReqTransferField pReqTransfer, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspOrderAction(CTPCommon::CThostFtdcInputOrderActionField pInputOrderAction, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspOrderInsert(CTPCommon::CThostFtdcInputOrderField pInputOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspParkedOrderAction(CTPCommon::CThostFtdcParkedOrderActionField pParkedOrderAction, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspParkedOrderInsert(CTPCommon::CThostFtdcParkedOrderField pParkedOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryBrokerTradingAlgos(CTPCommon::CThostFtdcBrokerTradingAlgosField pBrokerTradingAlgos, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryBrokerTradingParams(CTPCommon::CThostFtdcBrokerTradingParamsField pBrokerTradingParams, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryCFMMCTradingAccountKey(CTPCommon::CThostFtdcCFMMCTradingAccountKeyField pCFMMCTradingAccountKey, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryContractBank(CTPCommon::CThostFtdcContractBankField pContractBank, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryDepthMarketData(CTPCommon::CThostFtdcDepthMarketDataField pDepthMarketData, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryExchange(CTPCommon::CThostFtdcExchangeField pExchange, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInstrument(CTPCommon::CThostFtdcInstrumentField pInstrument, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInstrumentCommissionRate(CTPCommon::CThostFtdcInstrumentCommissionRateField pInstrumentCommissionRate, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInstrumentMarginRate(CTPCommon::CThostFtdcInstrumentMarginRateField pInstrumentMarginRate, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInvestor(CTPCommon::CThostFtdcInvestorField pInvestor, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInvestorPosition(CTPCommon::CThostFtdcInvestorPositionField pInvestorPosition, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInvestorPositionCombineDetail(CTPCommon::CThostFtdcInvestorPositionCombineDetailField pInvestorPositionCombineDetail, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryInvestorPositionDetail(CTPCommon::CThostFtdcInvestorPositionDetailField pInvestorPositionDetail, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryNotice(CTPCommon::CThostFtdcNoticeField pNotice, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryOrder(CTPCommon::CThostFtdcOrderField pOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryParkedOrder(CTPCommon::CThostFtdcParkedOrderField pParkedOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryParkedOrderAction(CTPCommon::CThostFtdcParkedOrderActionField pParkedOrderAction, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQrySettlementInfo(CTPCommon::CThostFtdcSettlementInfoField pSettlementInfo, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQrySettlementInfoConfirm(CTPCommon::CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTrade(CTPCommon::CThostFtdcTradeField pTrade, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTradingAccount(CTPCommon::CThostFtdcTradingAccountField pTradingAccount, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTradingCode(CTPCommon::CThostFtdcTradingCodeField pTradingCode, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTradingNotice(CTPCommon::CThostFtdcTradingNoticeField pTradingNotice, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTransferBank(CTPCommon::CThostFtdcTransferBankField pTransferBank, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryTransferSerial(CTPCommon::CThostFtdcTransferSerialField pTransferSerial, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQryAccountregister(CTPCommon::CThostFtdcAccountregisterField pAccountregister, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQueryBankAccountMoneyByFuture(CTPCommon::CThostFtdcReqQueryAccountField pReqQueryAccount, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspQueryMaxOrderVolume(CTPCommon::CThostFtdcQueryMaxOrderVolumeField pQueryMaxOrderVolume, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspRemoveParkedOrder(CTPCommon::CThostFtdcRemoveParkedOrderField pRemoveParkedOrder, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspRemoveParkedOrderAction(CTPCommon::CThostFtdcRemoveParkedOrderActionField pRemoveParkedOrderAction, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspSettlementInfoConfirm(CTPCommon::CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspTradingAccountPasswordUpdate(CTPCommon::CThostFtdcTradingAccountPasswordUpdateField pTradingAccountPasswordUpdate, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspAuthenticate(CTPCommon::CThostFtdcRspAuthenticateField pRspAuthenticateField, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspUserLogin(CTPCommon::CThostFtdcRspUserLoginField pRspUserLogin, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspUserLogout(CTPCommon::CThostFtdcUserLogoutField pUserLogout, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RspUserPasswordUpdate(CTPCommon::CThostFtdcUserPasswordUpdateField pUserPasswordUpdate, CTPCommon::CThostFtdcRspInfoField pRspInfo, int nRequestID, bool bIsLast);
public delegate void RtnErrorConditionalOrder(CTPCommon::CThostFtdcErrorConditionalOrderField pErrorConditionalOrder);
public delegate void RtnFromBankToFutureByBank(CTPCommon::CThostFtdcRspTransferField pRspTransfer);
public delegate void RtnFromBankToFutureByFuture(CTPCommon::CThostFtdcRspTransferField pRspTransfer);
public delegate void RtnFromFutureToBankByBank(CTPCommon::CThostFtdcRspTransferField pRspTransfer);
public delegate void RtnFromFutureToBankByFuture(CTPCommon::CThostFtdcRspTransferField pRspTransfer);
public delegate void RtnInstrumentStatus(CTPCommon::CThostFtdcInstrumentStatusField pInstrumentStatus);
public delegate void RtnOrder(CTPCommon::CThostFtdcOrderField pOrder);
public delegate void RtnQueryBankBalanceByFuture(CTPCommon::CThostFtdcNotifyQueryAccountField pNotifyQueryAccount);
public delegate void RtnRepealFromBankToFutureByBank(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnRepealFromBankToFutureByFuture(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnRepealFromBankToFutureByFutureManual(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnRepealFromFutureToBankByBank(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnRepealFromFutureToBankByFuture(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnRepealFromFutureToBankByFutureManual(CTPCommon::CThostFtdcRspRepealField pRspRepeal);
public delegate void RtnTrade(CTPCommon::CThostFtdcTradeField pTrade);
public delegate void RtnTradingNotice(CTPCommon::CThostFtdcTradingNoticeInfoField pTradingNoticeInfo);